### ISSUE TITLE
Support CherryTree format 

### ISSUE THREAD

**Issue by ls4cfk** [dsopas/assessment-mindset#9]
Cherrytree is very popular tool for penetration testers, it would be great if we had cherrytree format support.

**Comment by dsopas** [comment]
What formats would Cherrytree appects? opml? freemind? 
I would export it but I need to know the right format.

Thanks and I appreciate your feedback.

**Comment by ls4cfk** [comment]
It supports those formats -> https://imgur.com/2ZXlrpm
If it is impossible to export relevant format, I will try to convert it manually or something..

**Comment by dsopas** [comment]
I expected at least XML format. 
I think it would work with HTML - [https://github.com/dsopas/assessment-mindset/blob/dev/assessment-mindset.html](https://github.com/dsopas/assessment-mindset/blob/dev/assessment-mindset.html)

**Comment by ls4cfk** [comment]
It does not work. Only creates one node and inserts everything on it.

**Comment by dsopas** [comment]
So no luck. OPML and FreeMind formats are usually the open-source stuff that could be used to connect other tools. It seems that Cherrytree don't support them. Its out of my league @ls4cfk

**Comment by ls4cfk** [comment]
Understandable, I will try to export it manually.
